# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'ConstantWork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConstantWork
  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'

  # UI
  pod 'SnapKit'
  pod 'Then'

  # Reactor
  pod 'ReactorKit'

end
